### ISSUE TITLE
No Transaction ID saved

### ISSUE THREAD

**Issue by wucherpfennig** [pfpayments/prestashop-1.6#13]
Dear all

With the old module there was always a transaction id stored with an order. with this plugin this is not the case:

![grafik](https://github.com/pfpayments/prestashop-1.6/assets/3634653/55fbaa63-ea1a-4413-98b5-73792d1592b6)

This transaction ID is necessary in order to track the payouts by others like worldline.

How to fix?

BR wucherpfennig

**Comment by theodorspringwallee** [comment]
Dear [wucherpfennig](https://github.com/wucherpfennig)

We need to check your issue individually, for this please contact the PF Support directly:
https://www.postfinance.ch/de/support/hotline.html

Best regards

**Comment by wucherpfennig** [comment]
Thank you for your reply. 

Should there be a transaction id in the first place?

**Comment by wucherpfennig** [comment]
Thank you for your reply @theodorspringwallee 

Should there be a transaction id in the first place?

How do you come to this conclusion?

I mean there is some kind of transaction id: the module is able to link to the right transaction in the checkout website... Hence I assume there is one but not correctly stored in prestashop.

**Comment by theodorspringwallee** [comment]
Dear [wucherpfennig](https://github.com/wucherpfennig)

The PFC transaction should be linked to the PS order. About the order column of PS 1.6 with the transaction ID, we can't confirm.

Please consider that Prestashop 1.6 is already outdated since over 4 years: https://prestashop.com/blog/tech-en/end-of-maintenance-for-prestashop-1-6/

Therefore, it's more difficult for us to support such cases, and we definitely recommend upgrading to PS 1.7.

That we can check your case individually please contact the PF Support directly:  https://www.postfinance.ch/de/support/hotline.html

Best regards

**Comment by wucherpfennig** [comment]
@theodorspringwallee yes it is linked but why do you not store the PFC number in the column? No matter the prestashop version it is linked but not displayed...

**Comment by wucherpfennig** [comment]
This issue is not resolved... @theodorspringwallee

**Comment by wucherpfennig** [comment]
bump @theodorspringwallee 

The transaction id is well known: https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Helper.php#L533

https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Service/Transaction.php#L245

https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Service/Transaction.php#L278

the module also creates a table `pfc_transaction_info` in which the id is stored.

I do not know where you have to set the transaction id:

https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Webhook/Transaction.php#L88

https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Basemodule.php#L1617

or maybe here?

https://github.com/pfpayments/prestashop-1.6/blob/0bfe5d35cdcd04134a3d72ed56d1a0ac5ae40525/inc/Basemodule.php#L2405

I am able to provide a PR but you have to hint me in the right direction...

your help is greatly appreciated. Thank you
