### ISSUE TITLE
Payment selection displays two buttons, and both of them are not working

### ISSUE THREAD

**Issue by lmeyer1** [pfpayments/prestashop-1.6#5]
**Describe the bug**
When placing an order on Prestashop with Postfinance Checkout, the display of the page is not coherent, there are two buttons labelled `I confirm my order`, that do not have the same effect.
Additionally neither of both button confirms the order.

**To Reproduce**
On a default installation (see below for instructions for set up)
1. Open the shop with Chrome
1. Add a product to the cart
2. Place the order, on step `5. Paiement`, choose `Carte Postfinance`
3. Notice the strange display with the two buttons
4. Hit `F12` to open Chrome Dev Console
5. Click on the first button
6. Note the error in the Dev console

        checkout.js:90 Uncaught TypeError: Cannot read properties of undefined (reading 'processing')
        at HTMLButtonElement.handler_submit (checkout.js:90:22)
        at HTMLButtonElement.dispatch (jquery-1.11.0.min.js:3:8066)
        at HTMLButtonElement.r.handle (jquery-1.11.0.min.js:3:4767)

7. Click on the second button
8. An empty page displays, with an error in Dev console
![2022-01-28_152409](https://user-images.githubusercontent.com/7520695/151563551-329859fd-04c4-4803-b11b-787b17cf2a7f.jpg)
![2022-01-28_152420](https://user-images.githubusercontent.com/7520695/151563596-87c74fe6-c348-42cd-883e-a083fc6799fa.jpg)

**Expected behavior**
We should be able to place an order.

**Screenshots**
There are two buttons `I confirm my order`
![2022-01-28_152117](https://user-images.githubusercontent.com/7520695/151563002-a7e46eec-3d5a-44c8-adbc-277375dc2063.jpg)

**Software versions:**
 - Prestashop: 1.6.1.24, fresh install, default demo data.
 - Postfinance Checkout: 1.2.17, latest version as of today
 - PHP: 7.1.32

**Additional Info**

About the Javascript error: the offending lines in file `views/js/frontend/checkout.js` are:

        handler_submit : function (event) {
            if(!self.processing) {
                var self = event.data.self;
                self.disable_pay_button();

Obviously `var self = event.data.self;` should precede `if(!self.processing) {`

**Set up a clean installation**
If you do not have a test environment to reproduce this issue, this is how to set up a default installation:
- Get[ XAMPP Version 7.1.32 portable ](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.1.32/)
- Unzip [Prestashop 1.6.24 ](https://github.com/PrestaShop/PrestaShop/releases/tag/1.6.1.24)in C:\xampp\htdocs\prestashop-1.6.1.24
- In phpmyadmin create a database and a user
- Install Prestashop the standard way, choose Switzerland as a country
- In the BO, got to `Transport - Carriers` and activate the zone `Europe non-EU`for shipping (This is necessary to be able to place orders from Switzerland, we installed `Switzerland`).
- Install the latest version of Postfinance Checkout (currently 1.2.17)

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

Sorry for the late response.

Is this issue still relevant for you?

**Comment by lmeyer1** [comment]
Just a quick look at the code and the is still no translation in french. See https://github.com/pfpayments/prestashop-1.6/issues/4

Are you kidding? This product is for Switzerland. Do you ignore that Switzerland has four national languages and is not only german speaking?

**Comment by lmeyer1** [comment]
@theodorspringwallee 
You closed this issue as `Fixed`, what is not true. It would have been more honest to close it as `Won't fix`, wouldn't it ?
