### ISSUE TITLE
When placing an order, the articles remain in the cart, while the order stays in 'Processing' state

### ISSUE THREAD

**Issue by lmeyer1** [pfpayments/prestashop-1.6#6]
**Describe the bug**
When placing an order, after confirming the order, the articles of the order are still in the cart.

**To Reproduce**
1. Put an article into the cart
2. Place an order, selecting `Postfinance Card` as payment method
3. Click on the first button `I confirm my order`.
4. Notice that the order is complete and that the cart still contains the same article
5. Log into the BO
6. Go to the list of the orders
7. Notice that the order is in `Postfinance Checkout Processing` state

**Expected behavior**
After placing an order, the cart must be empty

**Screenshots**
Order is complete, but cart still contains the ordered article:
![2022-01-28_164441](https://user-images.githubusercontent.com/7520695/151577232-2d46e3ed-6d97-43bb-af89-5eb36badd1e4.jpg)
The order remains in `Postfinance Checkout Processing` state
![2022-01-28_165231](https://user-images.githubusercontent.com/7520695/151578653-bf155316-3e0f-4831-b1cb-bb6bea3dd426.jpg)

**Software versions (please complete the following information):**

- Prestashop: 1.6.1.24, fresh install, default demo data.
- Postfinance Checkout: 1.2.17, latest version as of today, with PR https://github.com/pfpayments/prestashop-1.6/pull/3 applied
- PHP: 7.1.32

**Additional information**

This is how to set up the test installation:
- Get[ XAMPP Version 7.1.32 portable ](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.1.32/)
- Unzip [Prestashop 1.6.24 ](https://github.com/PrestaShop/PrestaShop/releases/tag/1.6.1.24)in C:\xampp\htdocs\prestashop-1.6.1.24
- In phpmyadmin create a database and a user
- Install Prestashop the standard way, choose Switzerland as a country
- In the BO, got to `Transport - Carriers` and activate the zone `Europe non-EU`for shipping (This is necessary to be able to place orders from Switzerland, we installed `Switzerland`).
- Install the latest version of Postfinance Checkout (currently 1.2.17)

**Comment by lmeyer1** [comment]
When applying https://github.com/pfpayments/prestashop-1.6/pull/11, the state of the order evolves to become `Postfinance Checkout Authorized` and then `Payment accepted`.
Nevertheless, the main problem still remains: **When placing an order, the articles remain in the cart** (or a new cart is created with the same articles in it).

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

Sorry for the late response.

Is this issue still relevant for you?

**Comment by lmeyer1** [comment]
As explained here https://github.com/pfpayments/prestashop-1.6/issues/9#issuecomment-1262318210 this question comes too late.

Of course your mess is not working at all. Of course I lost hundreds of hours with it.
But I don't care anymore if you fixed something since then

**Comment by lmeyer1** [comment]
@theodorspringwallee 
You closed this issue as `Fixed`, what is not true. It would have been more honest to close it as `Won't fix`, wouldn't it ?
