### ISSUE TITLE
Configuration settings are wrongly saved in multishop context

### ISSUE THREAD

**Issue by lmeyer1** [pfpayments/prestashop-1.6#7]
**Describe the bug**
In multishop context, the configuration setting `PFC_MANUAL_TASKS` is set to `0` for all shops during installation, even if the module is installed in only one of the shops.

Additionally, the field `id_shop_group` is not set accordingly to the shop group of the shop the setting belongs to. Everywhere, the shop group is set to the shop where the module was installed. It is easier to understand with an example:

**Expected behavior**
1. The configuration settings must be saved only for the shops where `Postfinance Checkout` is installed and activated.
2. In the table `PREFIX_configuration`, on each line, the field `id_shop_group` must match the shop group of the shop `id_shop`. 

**To Reproduce**
1. Create a multishop install in Prestashop with shop 1 in shop group 1 and shop 2 in shop group 2.
2. Install Postfinance Checkout 1.6, version 1.2.17
3. Go to phpmyadmin and notice how the settings with name `PFC_MANUAL_TASKS` are stored in the table `PREFIX_configuration`:

| id_configuration | id_shop_group | id_shop | name | value | date_add | date_upd |
| - | - | - | -| - | - | - |
| - | 2* | 1 | PFC_MANUAL_TASKS | 0 | - | - |
| - | 2 | 2 | PFC_MANUAL_TASKS | 0 | - | - |

*: This is wrong, because shop 1 is in group 1. And in the first place, this line should not even be saved.

**Software versions (please complete the following information):**
 - Prestashop: 1.6, reproduced with v.1.6.1.1 and 1.6.1.24
 - Postfinance Checkout: latest version 1.2.17
 - PHP: reproduced with 7.1.32 and 7.2.34

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

Sorry for the late response.

Is this issue still relevant for you?

**Comment by lmeyer1** [comment]
No. We left your solution. We were forced by the missing support and the uncountable bugs.

**Comment by lmeyer1** [comment]
@theodorspringwallee 
You closed this issue as `Fixed`, what is not true. It would have been more honest to close it as `Won't fix`, wouldn't it ?
