### ISSUE TITLE
PostFinanceCheckoutWebhookModuleFrontController::postProcess throws an Exception with an empty message

### ISSUE THREAD

**Issue by lmeyer1** [pfpayments/prestashop-1.6#8]
**Describe the bug**

`GET /module/postfinancecheckout/webhook` gives an error 500, with the error `Property PrestaShopLogger->message is empty`
![image](https://user-images.githubusercontent.com/7520695/154998576-ce4dac60-90a2-4058-84f8-8212c964b4dc.png)

Looking closer, this is because `PostFinanceCheckoutWebhookModuleFrontController::postProcess` throws an `Exception` with an empty message.
This is because https://github.com/pfpayments/prestashop-1.6/blob/master/inc/Exception/Incompleteconfig.php does not specify a default message, and no message is defined at invocation neither https://github.com/pfpayments/prestashop-1.6/blob/7c90efc95453ba94a3653ecd0c67b1037c22d093/inc/Helper.php#L45

**Expected behavior**

Any Exception anywhere in any PHP program is supposed to have a message. This only allows for a straight forward debugging.

**To Reproduce**

1. Create a multishop installation of Prestashop
2. Configure Postfinance Checkout in a shop different from the first.
3. The webhook will throw an error 500.
4. Look at the error log on the server.

**Software versions (please complete the following information):**
 - Prestashop: 1.6, reproduced with v.1.6.1.1 and 1.6.1.24
 - Postfinance Checkout: latest version 1.2.18
 - PHP: reproduced with 7.1.32 and 7.2.34

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

Thank you for this discovered BUG. 

We will try to reproduce it on our side and give you feedback, if we get further information.

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

According to our devs, the plugin multi-shop setup for PS 1.6 is a not supported feature.

Therefore, we will close this issue.

**Comment by lmeyer1** [comment]
I just cannot understand this.

1. You (website of Postfinance and Checkout Flex manual) advertise that your module is fully compatible with PrestaShop. Multishop is a basic feature of Prestashop, and Prestashop standards requires to declare if a module is not compatible with multishop. Your module is NOT compatible with Prestashop multishop, and you do not declare, this means that you induce your future customers into error.
2. Your support (Postfinance) claimed repeatedly over several months, that the module is compatible with multishop configuration. 

Please advertise your product honestly. Support honestly and tell if something does not work. Hire developers who are working, and fire those that just say *Doesn't work* in order to shirk work.

And finally, coordinate marketing, support and development. Don't sell what you won't develop: that is deceiving people.

**Comment by lmeyer1** [comment]
@theodorspringwallee 
I just cannot understand this.

- You (website of Postfinance and Checkout Flex manual) advertise that your module is fully compatible with PrestaShop. Multishop is a basic feature of Prestashop, and Prestashop standards requires to declare if a module is not compatible with multishop. Your module is NOT compatible with Prestashop multishop, and you do not declareit, this means that you induce your future customers into error.
- Your support (Postfinance) claimed repeatedly over several months, that the module is compatible with multishop configuration.

Please advertise your product honestly. Support honestly and tell if something does not work. Hire developers who are working, and fire those that just say Doesn't work in order to shirk work.

And finally, coordinate marketing, support and development. Don't sell what you won't develop: that is deceiving people.

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

You definitely raised a good point. We apologize for the inconvenience, for this misinformation on our website.
We will adjust this.

Best regards

**Comment by lmeyer1** [comment]
@theodorspringwallee 
Thank you very much for your apologizing. It is soothing after almost a year of failing communication.

I'd like to apologize too for the harsh tone in my past answers.

Unfortunately for your business, we were forced to look for an alternative some months ago. The failure of your technical support and absence of reaction here on github where the main reasons for this decision.
