### ISSUE TITLE
The webhook URL always points to shop #1, thus Postfinance Checkout cannot work on any other shop

### ISSUE THREAD

**Issue by lmeyer1** [pfpayments/prestashop-1.6#9]
**Describe the bug**
The webhook URL created by the module always uses the URL of the `shop #1`.
In a multishop environment, when Postfinance Checkout is installed in any other shop, the webhook URL will point to the `shop #1`, and thus the payment process will not work.
When Postfinance's servers make their request to the webhook URL, an error 500 is returned, and thus the payment does not succeed.

**To Reproduce**
1. On a Prestashop multishop environment, with shop 1 on example.com and shop 2 on example.net, install and configure Postfinance Checkout on shop 2 (domain `example.net`)
2. Log into your account on https://checkout.postfinance.ch/
3. Under *Webhooks - URL* notice the new entry pointing to `https://example.com/module/postfinancecheckout/webhook`, the URL of `shop #1`. The webhook should of course use the domain of the shop where Postfinance Checkout Flex is configured. 

**Expected behavior**
I expect the Postfinance Checkout module pfpayment to work for every shop in a multishop installation, not only shop 1.

**Software versions (please complete the following information):**
 - Prestashop: 1.6.1.24
 - Postfinance Checkout: latest version 1.2.18
 - PHP: 7.2.34

**Comment by theodorspringwallee** [comment]
Dear [lmeyer1](https://github.com/lmeyer1)

Sorry for your late response

Is this still an issue/missing feature for you?

**Comment by lmeyer1** [comment]
@theodorspringwallee 
Sorry to say, we had to leave your product and Postfinance altogether.
I was chasing after you from december 2021 until this summer. I lost hundreds of hours trying to debug your mess and trying to get feedback form the support. We had even a video meeting with PF and one of your collegue. 
There we understood, that your company is not providing a serious collaboration, but is just leading everyone astray, trying to gain some time and money without working. I never saw something like that. 

Don't take it personnaly, it's perhaps not your fault, but wallee is just sucking !!!!

**Comment by lmeyer1** [comment]
@theodorspringwallee 
You closed this issue as `Fixed`, what is not true. It would have been more honest to close it as `Won't fix`, wouldn't it ?
